DROP TABLE MEMBER;

CREATE TABLE MEMBER(
    MEMBER_NO NUMBER NOT NULL
,   EMAIL VARCHAR2(400) NOT NULL
,   MEMBER_NAME VARCHAR2(500) NOT NULL
,   PWD VARCHAR2(200) NOT NULL
,   CRE_DATE DATE NOT NULL
,   MOD_DATE DATE NOT NULL
);

COMMENT ON TABLE MEMBER IS '회원기본정보';

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.PWD IS '암호';
COMMENT ON COLUMN MEMBER.CRE_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.MOD_DATE IS '마지막정보 변경일';


ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_MEMBER_NO_PK PRIMARY KEY(MNO);

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_EMAIL_UK UNIQUE(EMAIL);

DROP SEQUENCE MEMBER_NO_SEQ;
CREATE SEQUENCE MEMBER_NO_SEQ
INCREMENT BY 1
START WITH 1;

INSERT INTO MEMBER
(MEMBER_NO, EMAIL, MEMBER_NAME, PWD, CRE_DATE, MOD_DATE)
VALUES(MEMBER_NO_SEQ.NEXTVAL, 's1@test.com', '홍길동', '1111', SYSDATE, SYSDATE);

INSERT INTO MEMBER
(MEMBER_NO, EMAIL, MEMBER_NAME, PWD, CRE_DATE, MOD_DATE)
VALUES(MEMBER_NO_SEQ.NEXTVAL, 's2@test.com', '임꺽정', '1111', SYSDATE, SYSDATE);

INSERT INTO MEMBER
(MEMBER_NO, EMAIL, MEMBER_NAME, PWD, CRE_DATE, MOD_DATE)
VALUES(MEMBER_NO_SEQ.NEXTVAL, 's3@test.com', '일지매', '1111', SYSDATE, SYSDATE);

INSERT INTO MEMBER
(MEMBER_NO, EMAIL, MEMBER_NAME, PWD, CRE_DATE, MOD_DATE)
VALUES(MEMBER_NO_SEQ.NEXTVAL, 's4@test.com', '이몽룡', '1111', SYSDATE, SYSDATE);

INSERT INTO MEMBER
(MEMBER_NO, EMAIL, MEMBER_NAME, PWD, CRE_DATE, MOD_DATE)
VALUES(MEMBER_NO_SEQ.NEXTVAL, 's5@test.com', '성춘향', '1111', SYSDATE, SYSDATE);

select *
from member;

DESC MEMBER;

commit;

