--apple 계정에서 수행
CREATE TABLE APPLE (
    APPLE_SEQ NUMBER PRIMARY KEY,
    APPLE_NAME VARCHAR2(2000) NOT NULL,
    APPLE_PRICE NUMBER NOT NULL
);

DESC APPLE;

INSERT INTO APPLE
(APPLE_SEQ, APPLE_NAME, APPLE_PRICE)
VALUES(1, '사과', 12000);

COMMIT;

SELECT *
FROM APPLE
WHERE APPLE_SEQ = 1;

INSERT INTO APPLE
(APPLE_SEQ, APPLE_NAME, APPLE_PRICE)
VALUES(2, '배', 15000);

COMMIT;