CREATE TABLE DEPT1
AS
SELECT *
FROM DEPT
WHERE 1 = 0;

drop sequence DEPT1_DEPTNO_SEQ;

create SEQUENCE DEPT1_DEPTNO_SEQ
START WITH 10
INCREMENT BY 1;

DESC DEPT1;

INSERT INTO DEPT1
VALUE(DEPTNO, DNAME, LOC)
VALUES(99, 'A', 'A');

INSERT INTO DEPT1
VALUE(DEPTNO, DNAME, LOC)
VALUES(DEPT1_DEPTNO_SEQ.NEXTVAL, 'A', 'A');

select DEPT1_DEPTNO_SEQ.currval
from dual;

select *
from dept1;

ROLLBACK;