SELECT POSITION, COUNT(*), COUNT(HEIGHT), MAX(HEIGHT), MIN(HEIGHT), ROUND(AVG(HEIGHT), 2) 평균키
FROM PLAYER
GROUP BY POSITION
HAVING MAX(HEIGHT) >= 190;

SELECT POSITION, COUNT(*), COUNT(HEIGHT), MAX(HEIGHT), MIN(HEIGHT), ROUND(AVG(HEIGHT), 2) 평균키
FROM PLAYER
GROUP BY POSITION
HAVING NOT MAX(HEIGHT) >= 190;


SELECT *
FROM EMP;

SELECT *
FROM EMP
ORDER BY SAL ASC;

SELECT *
FROM EMP
ORDER BY SAL DESC;

SELECT *
FROM EMP
ORDER BY SAL;

SELECT *
FROM EMP
ORDER BY ENAME;

--사원테이블에서 급여가 작은 순인데 만약 급여가 같다면 사원의 이름이 빠른 순으로 출력한다
SELECT *
FROM EMP
ORDER BY SAL, ENAME ASC;

SELECT empno, ename
FROM EMP
ORDER BY mgr;

SELECT  dname DEPT, loc AREA, deptno
FROM DEPT
ORDER BY dname ASC, loc ASC, deptno DESC;

SELECT  dname DEPT, loc AREA, deptno, 1 aas
FROM DEPT
ORDER BY dept, area ASC, 3 DESC, aas;

SELECT job, SUM(sal) AS total_sal, count(job)
FROM emp
GROUP BY job
HAVING COUNT(*) > 0
order by total_sal desc;