
--제약조건 확인하기 -> 데이터 딕셔너리 중 하나 
SELECT *
FROM USER_CONSTRAINTS;

DESC USER_CONSTRAINTS;

SELECT OWNER, TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS;


DROP TABLE EMP1;

DESC EMP;

CREATE TABLE EMP1(
    E_NO NUMBER(4),
    E_NAME VARCHAR2(10),
    JOB VARCHAR2(9),
    D_NO NUMBER(2)
);

SELECT *
FROM EMP1;

INSERT INTO EMP1
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(NULL, NULL, 'SALESMAN', 30);

SELECT *
FROM EMP1;

DESC EMP1;

---------------
DROP TABLE EMP2;

DESC EMP;

CREATE TABLE EMP2(
    E_NO NUMBER(4) NOT NULL,
    E_NAME VARCHAR2(10) CONSTRAINT EMP2_E_NAME_NN NOT NULL,
    JOB VARCHAR2(9),
    D_NO NUMBER(2)
);

SELECT *
FROM EMP2;

INSERT INTO EMP2
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(NULL, NULL, 'SALESMAN', 30);

SELECT *
FROM EMP2;

DESC EMP2;

INSERT INTO EMP2
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(1111, '유빈', 'SALESMAN', 30);

SELECT *
FROM EMP2;


----------------------
DROP TABLE EMP3;

DESC EMP;

CREATE TABLE EMP3(
    E_NO NUMBER(4) UNIQUE,
    E_NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    D_NO NUMBER(2) CONSTRAINT EMP3_D_NO_UK UNIQUE
);

SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'EMP3';

DESC EMP3;

SELECT *
FROM EMP;

INSERT INTO EMP3
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369, 'SMITH', 'SALESMAN', 30);

INSERT INTO EMP3
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369+1, 'JONES', 'MANAGER', 20);

SELECT *
FROM EMP3;

DESC EMP3;

INSERT INTO EMP3
VALUE(E_NAME, JOB, D_NO)
VALUES('말리부', 'MANAGER', 20);

SELECT *
FROM EMP3;

INSERT INTO EMP2
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369, 'SMITH', 'SALESMAN', 30);

INSERT INTO EMP2
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369, 'SMITH', 'SALESMAN', 30);

SELECT *
FROM EMP2;

SELECT *
FROM user_constraints;


-----------------------

DROP TABLE EMP4;

DESC EMP;

CREATE TABLE EMP4(
    E_NO NUMBER(4) CONSTRAINT EMP4_E_NO_PK PRIMARY KEY,
    E_NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    D_NO NUMBER(2) CONSTRAINT EMP4_D_NO_UK UNIQUE NOT NULL
);

SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'EMP4';

DESC EMP4;

SELECT *
FROM EMP;

INSERT INTO EMP4
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369, 'SMITH', 'SALESMAN', 30);

INSERT INTO EMP4
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369, 'JONES', 'MANAGER', 20);

INSERT INTO EMP4
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369 + 1, 'JONES', 'MANAGER', 20);

INSERT INTO EMP4
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369 + 2, 'JONES', 'MANAGER', 20);

SELECT *
FROM EMP4;

DESC EMP4;

INSERT INTO EMP4
VALUE(E_NAME, JOB, D_NO)
VALUES('말리부', 'MANAGER', 40);

INSERT INTO EMP4
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(5, '말리부', 'MANAGER', NULL);

SELECT *
FROM EMP4;


SELECT *
FROM user_constraints;

DESC user_constraints;
-----------------------

SELECT OWNER, TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME, SEARCH_CONDITION
, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP5'
OR TABLE_NAME = 'DEPT5';


DROP TABLE EMP5; 
DROP TABLE DEPT5; 

SELECT *
FROM DEPT;

DESC DEPT;

CREATE TABLE DEPT5(
   D_NO NUMBER(2) PRIMARY KEY,
   DNAME VARCHAR2(14),
   LOC   VARCHAR2(13) 
);

INSERT INTO DEPT5
VALUES(10, 'ACCOUNTING', '');

INSERT INTO DEPT5
VALUES(20, 'RESEARCH', '');

INSERT INTO DEPT5
VALUES(30, 'SALES', '');

INSERT INTO DEPT5
VALUES(40, 'OPERATIONS', '');

SELECT *
FROM DEPT5;

DESC EMP;

DROP TABLE DEPT5 CASCADE CONSTRAINT;

CREATE TABLE EMP5(
    E_NO NUMBER(4) CONSTRAINT EMP5_E_NO_PK PRIMARY KEY,
    E_NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    D_NO NUMBER(2) CONSTRAINT EMP5_DEPT5_D_NO_FK 
        REFERENCES DEPT5(D_NO) 
);
--표현식
--내 컬럼명 데이터타입 CONSTRAINT 내테이블명_상대방테이블명_동일컬럼명_FK 
--        REFERENCES 상대방테이블명(컬럼명)

SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'EMP5';

DESC EMP5;

SELECT *
FROM EMP;

INSERT INTO EMP5
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7369, 'SMITH', 'SALESMAN', 30);

INSERT INTO EMP5
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7370, 'JONES', 'MANAGER', 20);

INSERT INTO EMP5
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7371, 'JONES', 'MANAGER', 40);

INSERT INTO EMP5
VALUE(E_NO, E_NAME, JOB, D_NO)
VALUES(7372, 'JONES', 'MANAGER', NULL);

SELECT *
FROM EMP5;

DESC EMP5;

SELECT OWNER, TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME, SEARCH_CONDITION
, R_CONSTRAINT_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMP5'
OR TABLE_NAME = 'DEPT5';

SELECT *
FROM DEPT5;
SELECT *
FROM EMP5;




-------------------

DROP TABLE EMP6;

DESC EMP;

CREATE TABLE EMP6(
    E_NO NUMBER(4) PRIMARY KEY,
    E_NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    SAL NUMBER(7, 2) CONSTRAINT EMP6_SAL_CK CHECK(SAL >= 500 AND SAL <= 5000),
    GENDER VARCHAR2(1) CHECK(GENDER IN('M', 'F'))   
,   D_NO NUMBER(2) DEFAULT 10
);

SELECT *
FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'EMP6';

DESC EMP6;

SELECT *
FROM EMP;

INSERT INTO EMP6
VALUE(E_NO, E_NAME, JOB, SAL, GENDER, D_NO)
VALUES(7369, 'SMITH', 'SALESMAN', 500, 'M', 30);

INSERT INTO EMP6
VALUE(E_NO, E_NAME, JOB, SAL, GENDER, D_NO)
VALUES(7369+1, 'SMITH', 'SALESMAN', 7500, 'M', 30);

INSERT INTO EMP6
VALUE(E_NO, E_NAME, JOB, SAL, GENDER, D_NO)
VALUES(7369+2, 'SMITH', 'SALESMAN', 500, 'A', 30);

INSERT INTO EMP6
VALUE(E_NO, E_NAME, JOB, SAL, GENDER)
VALUES(7369+2, 'SMITH', 'SALESMAN', 500, 'F');

SELECT *
FROM EMP6;

DESC EMP6;

SELECT *
FROM EMP6;


SELECT *
FROM user_constraints;

------------------

--제약조건 변경하기
SELECT *
FROM user_constraints
WHERE TABLE_NAME = 'EMP7';

CREATE TABLE EMP7
AS
SELECT *
FROM EMP6
WHERE 1 = 0;

SELECT *
FROM EMP7;

DESC EMP7;

--제약조건 추가하기
ALTER TABLE EMP7
ADD CONSTRAINT EMP7_E_NO_PK PRIMARY KEY(E_NO);

CREATE TABLE DEPT7
AS
SELECT *
FROM DEPT5
WHERE 1 = 0;

ALTER TABLE DEPT7
ADD CONSTRAINT DEPT7_D_NO_PK PRIMARY KEY(D_NO);

ALTER TABLE EMP7
ADD CONSTRAINT EMP7_DEPT7_D_NO_FK 
FOREIGN KEY(D_NO) REFERENCES DEPT7(D_NO);

SELECT *
FROM user_constraints
WHERE TABLE_NAME LIKE '%7';

DESC DEPT7;

--NOT NULL은 특이한 제약조건이다. 
ALTER TABLE DEPT7
MODIFY DNAME NOT NULL;

ALTER TABLE DEPT7
MODIFY DNAME NULL;

--제약조건 제거하기
ALTER TABLE EMP7
DROP CONSTRAINT EMP7_E_NO_PK;




