-- PASSBOOK(통장 테이블)에서 사용할 SEQUENCE
CREATE SEQUENCE PASSBOOK_ACCOUNT_NUMBER_SQE
START WITH 11
INCREMENT BY 1;

-- PASSBOOK TABLE CREATE
CREATE TABLE PASSBOOK (
  ACCOUNT_NUMBER NUMBER(20) CONSTRAINT PASSBOOK_ACCOUNT_NUMBER_PK PRIMARY KEY,
  ACCOUNT_NAME VARCHAR2(100) NOT NULL,
  BANK_BALANCE NUMBER(10, 2) DEFAULT 0
);

DESC PASSBOOK;

-- MY_EMP TABLE CREATE
CREATE TABLE MY_EMP
AS
SELECT *
FROM EMP;

DESC MY_EMP;

-- MONEY라는 각 사원 소지금 칼럼 생성
ALTER TABLE MY_EMP
ADD MONEY NUMBER(10) DEFAULT 0;

DESC MY_EMP;

-- 모든 사원은 기본적으로 급여의 10%를 소지금으로 가짐
UPDATE MY_EMP
SET MONEY = SAL * 0.1;

SELECT ENAME, MONEY
FROM MY_EMP;

-- 본인이 회사에 입사
INSERT INTO MY_EMP
VALUE(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES(
  8000, 'DOBBY', 'FE', 7902, SYSDATE, 5000, NULL, 40
);

-- 총 사원 13명

SELECT COUNT(EMPNO)
FROM MY_EMP;

-- 본인은 1000원을 가짐
UPDATE MY_EMP
SET MONEY = 1000
WHERE EMPNO = (SELECT EMPNO
               FROM MY_EMP
               WHERE ENAME = 'DOBBY');

SELECT *
FROM MY_EMP
WHERE EMPNO = (SELECT EMPNO
               FROM MY_EMP
               WHERE ENAME = 'DOBBY');

-- 통장에 적금으로 300원을 넣음
-- * 적금 넣기 전, 통장 개설을 따로 해주었음
INSERT INTO PASSBOOK
VALUE(ACCOUNT_NUMBER, ACCOUNT_NAME)
VALUES(PASSBOOK_ACCOUNT_NUMBER_SQE.NEXTVAL, 'DOBBY');

UPDATE MY_EMP
SET MONEY = MONEY - 300
WHERE EMPNO = (SELECT EMPNO
               FROM MY_EMP
               WHERE ENAME = 'DOBBY');

UPDATE PASSBOOK
SET BANK_BALANCE = BANK_BALANCE + 300
WHERE ACCOUNT_NUMBER = (SELECT ACCOUNT_NUMBER
                        FROM PASSBOOK
                        WHERE ACCOUNT_NAME = 'DOBBY');

SELECT * FROM MY_EMP;
SELECT * FROM PASSBOOK;

--  월급이 들어옴 => 500원 들어옴
UPDATE MY_EMP
SET MONEY = MONEY - 500
WHERE EMPNO = (SELECT EMPNO
               FROM MY_EMP
               WHERE ENAME = 'KING');

UPDATE MY_EMP
SET MONEY = MONEY + 500
WHERE EMPNO = (SELECT EMPNO
               FROM MY_EMP
               WHERE ENAME = 'DOBBY');

SELECT * FROM MY_EMP;

-- 통장에 200원을 넣음
UPDATE MY_EMP
SET MONEY = MONEY - 200
WHERE EMPNO = (SELECT EMPNO
               FROM MY_EMP
               WHERE ENAME = 'DOBBY');

UPDATE PASSBOOK
SET BANK_BALANCE = BANK_BALANCE + 200
WHERE ACCOUNT_NUMBER = (SELECT ACCOUNT_NUMBER
                        FROM PASSBOOK
                        WHERE ACCOUNT_NAME = 'DOBBY');

SELECT * FROM MY_EMP;
SELECT * FROM PASSBOOK;

-- 내가 가진 금액과 통장의 금액
SELECT ENAME, SAL, MONEY, ACCOUNT_NAME, BANK_BALANCE
FROM MY_EMP M INNER JOIN PASSBOOK P
ON M.ENAME = P.ACCOUNT_NAME;

--ROLLBACK;